version: '3'

services:
  frontend:
    build: /home/user/MyProjects/docker-course/time-app/frontend
    ports:
      - '3333:3000'
  api:
    build: /home/user/MyProjects/docker-course/time-app/api
    restart: always
    ports:
      - '5555:5000'
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATEBASE: time_db
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
    networks:
      - time-app

networks:
  time-app:
